# Generated by Django 4.1.1 on 2022-10-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('previstoSaida', models.DateTimeField(auto_now=True)),
                ('previstoChegada', models.DateTimeField(auto_now=True)),
                ('VooId', models.CharField(max_length=12)),
                ('localPartida', models.CharField(max_length=50)),
                ('destino', models.CharField(max_length=50)),
                ('aeroportoSaida', models.CharField(max_length=50)),
                ('aeroportoChegada', models.CharField(max_length=50)),
                ('compAerea', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Voo',
            },
        ),
    ]
