# Generated by Django 4.1.1 on 2022-10-06 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voo',
            name='estado',
        ),
        migrations.CreateModel(
            name='VooReal',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('realSaida', models.DateTimeField(auto_now=True)),
                ('realChegada', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(max_length=50)),
                ('voo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.voo')),
            ],
            options={
                'db_table': 'VooReal',
            },
        ),
    ]
