# Generated by Django 4.1.1 on 2022-10-06 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_remove_voo_estado_vooreal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voo',
            old_name='previstoChegada',
            new_name='DH_PREVISTO_CHEGADA',
        ),
        migrations.RenameField(
            model_name='voo',
            old_name='previstoSaida',
            new_name='DH_PREVISTO_SAIDA',
        ),
        migrations.RenameField(
            model_name='voo',
            old_name='id',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='voo',
            old_name='VooId',
            new_name='ID_VOO',
        ),
        migrations.RenameField(
            model_name='voo',
            old_name='aeroportoChegada',
            new_name='NM_AEROPORTO_CHEGADA',
        ),
        migrations.RenameField(
            model_name='voo',
            old_name='aeroportoSaida',
            new_name='NM_AEROPORTO_SAIDA',
        ),
        migrations.RenameField(
            model_name='voo',
            old_name='compAerea',
            new_name='NM_COMPANHIA_AEREA',
        ),
        migrations.RenameField(
            model_name='vooreal',
            old_name='realChegada',
            new_name='DH_REAL_CHEGADA',
        ),
        migrations.RenameField(
            model_name='vooreal',
            old_name='realSaida',
            new_name='DH_REAL_SAIDA',
        ),
        migrations.RenameField(
            model_name='vooreal',
            old_name='id',
            new_name='ID',
        ),
        migrations.RenameField(
            model_name='vooreal',
            old_name='voo',
            new_name='ID_VOO',
        ),
        migrations.RenameField(
            model_name='vooreal',
            old_name='estado',
            new_name='NM_STATUS',
        ),
        migrations.RemoveField(
            model_name='voo',
            name='destino',
        ),
        migrations.RemoveField(
            model_name='voo',
            name='localPartida',
        ),
    ]
