# Generated by Django 4.1.1 on 2022-10-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_rename_previstochegada_voo_dh_previsto_chegada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voo',
            name='DH_PREVISTO_CHEGADA',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='voo',
            name='DH_PREVISTO_SAIDA',
            field=models.DateTimeField(),
        ),
    ]
