# Generated by Django 4.1.2 on 2022-10-20 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_voo_dh_previsto_chegada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('ID_USUARIO', models.CharField(max_length=12)),
                ('FIRST_NAME', models.CharField(max_length=50)),
                ('LAST_NAME', models.CharField(max_length=50)),
                ('SENHA', models.CharField(max_length=50)),
                ('USER_PERMISSION', models.IntegerField()),
            ],
            options={
                'db_table': 'Usuario',
            },
        ),
    ]
