# Generated by Django 4.1.3 on 2022-11-30 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voo',
            options={'permissions': (('chang', 'chang voo'),)},
        ),
    ]
