# Generated by Django 4.1.3 on 2022-11-30 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voo',
            options={},
        ),
    ]
