# Generated by Django 4.1.3 on 2022-11-30 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_alter_voo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('access_relatorio', 'can access relatorio page'), ('generate_relatorio ', 'can generate relatorio'))},
        ),
    ]
