# Generated by Django 4.1.3 on 2022-11-30 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('access_relatorio', 'can access relatorio page'), ('generate_relatorio ', 'can generate relatorio'), ('access_atualizar', 'can access to atualizar voo page'))},
        ),
    ]
