# Generated by Django 4.1.3 on 2022-12-01 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_alter_vooreal_dh_real_chegada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vooreal',
            name='NM_STATUS',
            field=models.CharField(max_length=50, verbose_name=('pronto', ('cancelado',))),
        ),
    ]
