# Generated by Django 4.1.3 on 2022-12-01 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_alter_vooreal_nm_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vooreal',
            name='DH_REAL_CHEGADA',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='vooreal',
            name='DH_REAL_SAIDA',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='vooreal',
            name='NM_STATUS',
            field=models.CharField(max_length=50),
        ),
    ]
