# Generated by Django 4.1.3 on 2022-12-01 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_alter_vooreal_dh_real_chegada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vooreal',
            name='DH_REAL_CHEGADA',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='vooreal',
            name='DH_REAL_SAIDA',
            field=models.DateTimeField(),
        ),
    ]
