# Generated by Django 4.1.3 on 2022-12-01 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0016_alter_vooreal_id_voo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vooreal',
            name='ID_VOO',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.voo'),
        ),
    ]
