# Generated by Django 4.1.2 on 2022-12-01 17:56

import book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0017_alter_vooreal_id_voo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voo',
            name='NM_AEROPORTO_CHEGADA',
            field=models.CharField(max_length=50, validators=[book.models.Voo.clean]),
        ),
    ]
