# Generated by Django 4.1.2 on 2022-12-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0019_alter_voo_dh_previsto_chegada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voo',
            name='DH_PREVISTO_CHEGADA',
            field=models.DateTimeField(),
        ),
    ]
