# Generated by Django 4.1.2 on 2022-12-01 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0020_alter_voo_dh_previsto_chegada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('view_voo_atual', 'can view voo atual'), ('access_relatorio', 'can access relatorio page'), ('generate_relatorio ', 'can generate relatorio'), ('access_atualizar', 'can access to atualizar voo page'))},
        ),
    ]
