# Generated by Django 4.1.3 on 2022-12-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0022_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('access_relatorio', 'can access relatorio page'), ('generate_relatorio ', 'can generate relatorio'), ('access_atualizar', 'can access to atualizar voo page'))},
        ),
        migrations.AlterField(
            model_name='vooreal',
            name='NM_STATUS',
            field=models.CharField(choices=[('EM', 'Embarcando'), ('CA', 'Cancelado'), ('PR', 'Programado'), ('TA', 'Taxeando'), ('PO', 'Pronto'), ('AU', 'Autorizado'), ('VO', 'Em voo')], default='EM', max_length=50),
        ),
    ]
