# Generated by Django 4.1.3 on 2022-12-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0023_alter_user_options_alter_vooreal_nm_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vooreal',
            name='NM_STATUS',
            field=models.CharField(choices=[('EM', 'Embarcando'), ('CA', 'Cancelado'), ('PR', 'Programado'), ('TA', 'Taxeando'), ('PO', 'Pronto'), ('AU', 'Autorizado'), ('VO', 'Em voo'), ('PU', 'Pousando'), ('AT', 'Atterissado')], default='EM', max_length=50),
        ),
    ]
