# Generated by Django 4.1.3 on 2022-12-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0024_alter_vooreal_nm_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vooreal',
            name='NM_STATUS',
            field=models.CharField(choices=[('Programado', 'Programado'), ('Embarcando', 'Embarcando'), ('Cancelado', 'Cancelado'), ('Taxeando', 'Taxeando'), ('Pronto', 'Pronto'), ('Autorizado', 'Autorizado'), ('Em voo', 'Em voo'), ('Pousando', 'Pousando'), ('Atterissado', 'Atterissado')], default='Programado', max_length=50),
        ),
    ]
